import { type DeepPartial } from 'typeorm'
import { type User } from '../../Entities/user.entity.js'

export const userSeeds: Array<DeepPartial<User>> = [
  {
    email: 'user1@example.com',
    password: 'password1',
    nickname: 'UserOne',
    picture: 'https://pics.com/u1.jpg',
    name: 'Alice',
    surname: 'Smith',
    country: 'USA',
    isVerify: true,
    role: 1,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user2@example.com',
    password: 'password2',
    nickname: 'UserTwo',
    picture: 'https://pics.com/u2.jpg',
    name: 'Bob',
    surname: 'Johnson',
    country: 'Canada',
    isVerify: false,
    role: 2,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user3@example.com',
    password: 'password3',
    nickname: 'UserThree',
    picture: 'https://pics.com/u3.jpg',
    name: 'Carol',
    surname: 'Williams',
    country: 'UK',
    isVerify: true,
    role: 1,
    isRoot: false,
    enabled: false
  },
  {
    email: 'user4@example.com',
    password: 'password4',
    nickname: 'UserFour',
    picture: 'https://pics.com/u4.jpg',
    name: 'David',
    surname: 'Brown',
    country: 'Australia',
    isVerify: false,
    role: 2,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user5@example.com',
    password: 'password5',
    nickname: 'UserFive',
    picture: 'https://pics.com/u5.jpg',
    name: 'Eve',
    surname: 'Jones',
    country: 'Spain',
    isVerify: true,
    role: 1,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user6@example.com',
    password: 'password6',
    nickname: 'UserSix',
    picture: 'https://pics.com/u6.jpg',
    name: 'Frank',
    surname: 'Garcia',
    country: 'Mexico',
    isVerify: false,
    role: 2,
    isRoot: false,
    enabled: false
  },
  {
    email: 'user7@example.com',
    password: 'password7',
    nickname: 'UserSeven',
    picture: 'https://pics.com/u7.jpg',
    name: 'Grace',
    surname: 'Martinez',
    country: 'Argentina',
    isVerify: true,
    role: 1,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user8@example.com',
    password: 'password8',
    nickname: 'UserEight',
    picture: 'https://pics.com/u8.jpg',
    name: 'Hank',
    surname: 'Lopez',
    country: 'Chile',
    isVerify: false,
    role: 2,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user9@example.com',
    password: 'password9',
    nickname: 'UserNine',
    picture: 'https://pics.com/u9.jpg',
    name: 'Ivy',
    surname: 'Gonzalez',
    country: 'Peru',
    isVerify: true,
    role: 1,
    isRoot: false,
    enabled: false
  },
  {
    email: 'user10@example.com',
    password: 'password10',
    nickname: 'UserTen',
    picture: 'https://pics.com/u10.jpg',
    name: 'Jack',
    surname: 'Perez',
    country: 'Colombia',
    isVerify: false,
    role: 2,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user11@example.com',
    password: 'password11',
    nickname: 'UserEleven',
    picture: 'https://pics.com/u11.jpg',
    name: 'Karen',
    surname: 'Sanchez',
    country: 'Uruguay',
    isVerify: true,
    role: 1,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user12@example.com',
    password: 'password12',
    nickname: 'UserTwelve',
    picture: 'https://pics.com/u12.jpg',
    name: 'Leo',
    surname: 'Ramirez',
    country: 'Paraguay',
    isVerify: false,
    role: 2,
    isRoot: false,
    enabled: false
  },
  {
    email: 'user13@example.com',
    password: 'password13',
    nickname: 'UserThirteen',
    picture: 'https://pics.com/u13.jpg',
    name: 'Mona',
    surname: 'Torres',
    country: 'Venezuela',
    isVerify: true,
    role: 1,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user14@example.com',
    password: 'password14',
    nickname: 'UserFourteen',
    picture: 'https://pics.com/u14.jpg',
    name: 'Nate',
    surname: 'Flores',
    country: 'Bolivia',
    isVerify: false,
    role: 2,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user15@example.com',
    password: 'password15',
    nickname: 'UserFifteen',
    picture: 'https://pics.com/u15.jpg',
    name: 'Olga',
    surname: 'Rivera',
    country: 'Ecuador',
    isVerify: true,
    role: 1,
    isRoot: false,
    enabled: false
  },
  {
    email: 'user16@example.com',
    password: 'password16',
    nickname: 'UserSixteen',
    picture: 'https://pics.com/u16.jpg',
    name: 'Paul',
    surname: 'Gomez',
    country: 'Guatemala',
    isVerify: false,
    role: 2,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user17@example.com',
    password: 'password17',
    nickname: 'UserSeventeen',
    picture: 'https://pics.com/u17.jpg',
    name: 'Quinn',
    surname: 'Diaz',
    country: 'Honduras',
    isVerify: true,
    role: 1,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user18@example.com',
    password: 'password18',
    nickname: 'UserEighteen',
    picture: 'https://pics.com/u18.jpg',
    name: 'Rita',
    surname: 'Cruz',
    country: 'El Salvador',
    isVerify: false,
    role: 2,
    isRoot: false,
    enabled: false
  },
  {
    email: 'user19@example.com',
    password: 'password19',
    nickname: 'UserNineteen',
    picture: 'https://pics.com/u19.jpg',
    name: 'Sam',
    surname: 'Ortiz',
    country: 'Nicaragua',
    isVerify: true,
    role: 1,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user20@example.com',
    password: 'password20',
    nickname: 'UserTwenty',
    picture: 'https://pics.com/u20.jpg',
    name: 'Tina',
    surname: 'Morales',
    country: 'Costa Rica',
    isVerify: false,
    role: 2,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user21@example.com',
    password: 'password21',
    nickname: 'UserTwentyOne',
    picture: 'https://pics.com/u21.jpg',
    name: 'Uma',
    surname: 'Castro',
    country: 'Panama',
    isVerify: true,
    role: 1,
    isRoot: false,
    enabled: false
  },
  {
    email: 'user22@example.com',
    password: 'password22',
    nickname: 'UserTwentyTwo',
    picture: 'https://pics.com/u22.jpg',
    name: 'Vic',
    surname: 'Rojas',
    country: 'Cuba',
    isVerify: false,
    role: 2,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user23@example.com',
    password: 'password23',
    nickname: 'UserTwentyThree',
    picture: 'https://pics.com/u23.jpg',
    name: 'Will',
    surname: 'Mendez',
    country: 'Dominican Republic',
    isVerify: true,
    role: 1,
    isRoot: false,
    enabled: true
  },
  {
    email: 'user24@example.com',
    password: 'password24',
    nickname: 'UserTwentyFour',
    picture: 'https://pics.com/u24.jpg',
    name: 'Xena',
    surname: 'Silva',
    country: 'Puerto Rico',
    isVerify: false,
    role: 2,
    isRoot: false,
    enabled: false
  },
  {
    email: 'user25@example.com',
    password: 'password25',
    nickname: 'UserTwentyFive',
    picture: 'https://pics.com/u25.jpg',
    name: 'Yuri',
    surname: 'Navarro',
    country: 'Haiti',
    isVerify: true,
    role: 1,
    isRoot: true,
    enabled: true
  }
]
